version: '3.8'
services:
  postgresdb:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: gobank

    networks:
      - alx

networks:
  alx: